language: android
android:
  components:
    - platform-tools
    - tools
    - addon-google_apis-google-21
    - sys-img-armeabi-v7a-google_apis-google-21
before_script:
  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:21" --abi armeabi-v7a --tag google_apis
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
before_install:
  - android update project --target android-21 -p .
  - android update test-project -m ../ -p tests
  - cd tests