language: android
android:
  components:
    - platform-tools
    - tools
    - android-19
    - addon-google_apis-google-19
before_install: android update project --target android-19 --path .
install: ant debug
script: ls bin/*.apk | grep -i 'debug\.apk'
